#
# Fast Layer Dockerfile for Custom Kubeflow JupyterLab Image (CUDA GPU)
# Extends upstream ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-pytorch-cuda-full:v1.11.0
# Pinged to digest for better reproducibility

ARG BASE_IMG=ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-pytorch-cuda-full:v1.11.0@sha256:55f6abbe52112317570b9cd10967bc8e4dc724eaff7030bc92d97a2e097dce84
FROM $BASE_IMG

ARG TARGETARCH=amd64

# NVIDIA Container Toolkit environment variables
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

USER $NB_UID

ENV PATH="${HOME}/.local/bin:${PATH}"

# Configure Conda to persist environments and package caches on the persistent home volume (~/.conda)
RUN conda config --system --prepend envs_dirs '~/.conda/envs' \
 && conda config --system --prepend pkgs_dirs '~/.conda/pkgs'

# Install additional Python requirements for GPU (including jax[cuda12], kubeflow[spark], google-cloud-storage)
COPY --chown=${NB_USER}:${NB_GID} requirements-gpu.txt /tmp/requirements.txt
RUN PIP_NO_CACHE_DIR=off python3 -m pip install -r /tmp/requirements.txt --quiet --no-cache-dir \
 && rm -f /tmp/requirements.txt \
 && pip config --site set install.user true

# Pre-populate home with samples, and sync to $HOME_TMP for s6 01-copy-tmp-home
COPY --chown=${NB_USER}:${NB_GID} samples/. ${HOME}/samples/
RUN cp -p -r -T "${HOME}" "${HOME_TMP}" \
 && chmod -R g=u "${HOME_TMP}"
